name: 'Spring Gradle Build Action'
description: 'Reusable GitHub Action for performing a gradle build or running a gradle task.'
author: 'Spring'

inputs:
  java-version:
    description: 'Version of the JDK to use to run the Gradle command. Used in the actions/setup-java step.'
    required: false
    default: '17'
  distribution:
    description: 'Distribution of the JDK to use to run the Gradle command. Used in the actions/setup-java step.'
    required: false
    default: 'temurin'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4.7.0
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
    - name: Set up gradle user name
      shell: bash
      run: |
        mkdir -p $HOME/.gradle
        echo 'systemProp.user.name=spring-builds+github' >> $HOME/.gradle/gradle.properties
    - name: Gradle Wrapper Validation
      uses: gradle/actions/wrapper-validation@v4.3.1
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4.3.1
