name: Auto-Merge Dependabot PR

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'spring-io/spring-gradle-build-action' }}
    steps:
      - id: dependabot-metadata
        name: Dependabot Metadata
        uses: dependabot/fetch-metadata@v2.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --rebase "$PR_URL"
      - uses: actions/checkout@v5
      - name: Update v2 branch
        run: git fetch origin && git checkout --track origin/v2 && git merge origin/main && git push origin v2